#!/bin/bash

echo "📝 New file created:"
echo "  - RemindersService.swift"
echo ""
echo "⚠️  You need to add this file to Xcode:"
echo ""
echo "1. In Xcode, right-click on the 'Services' folder (Core > Services)"
echo "2. Select 'Add Files to Heirloom...'"
echo "3. Navigate to: Heirloom/Core/Services/"
echo "4. Select: RemindersService.swift"
echo "5. Ensure 'Add to targets: Heirloom' IS checked"
echo "6. Click 'Add'"
echo ""
echo "OR use drag and drop:"
echo "1. Open Finder and navigate to Heirloom/Core/Services/"
echo "2. Drag RemindersService.swift into Xcode's 'Services' folder"
echo "3. Ensure 'Add to targets: Heirloom' IS checked"
echo "4. Click 'Finish'"
echo ""
echo "Then rebuild the project (Cmd+B)"
