#!/bin/bash

echo "📝 New file created:"
echo "  - SettingsView.swift"
echo ""
echo "⚠️  You need to add this file to Xcode:"
echo ""
echo "1. In Xcode, right-click on the 'Features' folder"
echo "2. Select 'New Group' and name it 'Settings'"
echo "3. Right-click on the new 'Settings' folder"
echo "4. Select 'Add Files to Heirloom...'"
echo "5. Navigate to: Heirloom/Features/Settings/"
echo "6. Select: SettingsView.swift"
echo "7. Ensure 'Add to targets: Heirloom' IS checked"
echo "8. Click 'Add'"
echo ""
echo "OR use drag and drop:"
echo "1. Create a 'Settings' group inside 'Features' in Xcode"
echo "2. Open Finder and navigate to Heirloom/Features/Settings/"
echo "3. Drag SettingsView.swift into Xcode's 'Settings' folder"
echo "4. Ensure 'Add to targets: Heirloom' IS checked"
echo "5. Click 'Finish'"
echo ""
echo "Then rebuild the project (Cmd+B)"
