#!/bin/bash

echo "📝 New files created:"
echo "  - RecipeImportService.swift"
echo "  - RecipeImportView.swift"
echo ""
echo "⚠️  You need to add these files to Xcode:"
echo ""
echo "=== RecipeImportService.swift ==="
echo "1. In Xcode, right-click on the 'Services' folder (Core > Services)"
echo "2. Select 'Add Files to Heirloom...'"
echo "3. Navigate to: Heirloom/Core/Services/"
echo "4. Select: RecipeImportService.swift"
echo "5. Ensure 'Add to targets: Heirloom' IS checked"
echo "6. Click 'Add'"
echo ""
echo "=== RecipeImportView.swift ==="
echo "7. In Xcode, right-click on the 'Recipes' folder (Features > Recipes)"
echo "8. Select 'New Group' and name it 'RecipeImport'"
echo "9. Right-click on the new 'RecipeImport' folder"
echo "10. Select 'Add Files to Heirloom...'"
echo "11. Navigate to: Heirloom/Features/Recipes/RecipeImport/"
echo "12. Select: RecipeImportView.swift"
echo "13. Ensure 'Add to targets: Heirloom' IS checked"
echo "14. Click 'Add'"
echo ""
echo "Then rebuild the project (Cmd+B)"
echo ""
echo "✨ Features:"
echo "  - Import recipes from any major cooking website"
echo "  - Automatic parsing of ingredients and instructions"
echo "  - Image downloading and storage"
echo "  - Schema.org JSON-LD support (most reliable)"
echo "  - Fallback microdata parsing for older sites"
