#!/bin/bash

echo "📝 New files created:"
echo "  - IngredientParser.swift"
echo "  - SampleRecipeLibrary.swift"
echo ""
echo "⚠️  You need to add these files to Xcode:"
echo ""
echo "1. In Xcode, right-click on the 'Services' folder (Core > Services)"
echo "2. Select 'Add Files to Heirloom...'"
echo "3. Navigate to: Heirloom/Core/Services/"
echo "4. Select: IngredientParser.swift"
echo "5. Click 'Add'"
echo ""
echo "6. Right-click on the 'Data' folder (Core > Data)"
echo "7. Select 'Add Files to Heirloom...'"
echo "8. Navigate to: Heirloom/Core/Data/"
echo "9. Select: SampleRecipeLibrary.swift"
echo "10. Click 'Add'"
echo ""
echo "OR use drag and drop:"
echo "1. Open Finder and navigate to Heirloom/Core/Services/"
echo "2. Drag IngredientParser.swift into Xcode's 'Services' folder"
echo "3. Navigate to Heirloom/Core/Data/"
echo "4. Drag SampleRecipeLibrary.swift into Xcode's 'Data' folder"
echo "5. Ensure 'Add to targets: Heirloom' IS checked for both"
echo "6. Click 'Finish'"
echo ""
echo "Then rebuild the project (Cmd+B)"
