import Foundation
import CryptoKit

/// Tracks the origin, lineage, and sharing history of a recipe
/// Embedded as a Codable property within Recipe model
struct ProvenanceMetadata: Codable, Hashable {
    // MARK: - Source Origin

    /// Where this recipe came from
    var sourceType: SourceType

    /// Original URL if imported from web
    var sourceURL: String?

    /// Attribution text (e.g., "From AllRecipes.com", "Grandma Rose")
    var sourceAttribution: String?

    // MARK: - Lineage Tracking

    /// Unique hash identifying the root recipe in the share chain
    /// All copies/shares of the same original recipe have the same rootProvenanceHash
    /// Format: SHA256 of (originalTitle + originalCreatedAt + originalUserID)
    var rootProvenanceHash: String

    /// Generation in share chain:
    /// - 0: Original recipe (user created or imported)
    /// - 1: First-level share (shared directly from original)
    /// - 2+: Re-shared copies
    var generation: Int

    /// CKShare record ID of the parent share (if this is a received share)
    /// Used to link back to the sharing parent
    var parentShareID: String?

    /// Display name of person who shared this (if generation > 0)
    var sharedByName: String?

    /// Date when this specific copy was created
    var createdAt: Date

    // MARK: - CloudKit Sync

    /// CKRecord ID in CloudKit (if synced to public database)
    var cloudKitRecordID: String?

    /// Last time this recipe's metadata was synced with CloudKit
    var lastSyncedAt: Date?

    /// Cached aggregated metrics from CloudKit
    var cachedMetrics: AggregatedMetrics

    // MARK: - Initialization

    init(
        sourceType: SourceType,
        sourceURL: String? = nil,
        sourceAttribution: String? = nil,
        rootProvenanceHash: String? = nil,
        generation: Int = 0,
        parentShareID: String? = nil,
        sharedByName: String? = nil,
        createdAt: Date = Date(),
        cloudKitRecordID: String? = nil,
        lastSyncedAt: Date? = nil,
        cachedMetrics: AggregatedMetrics = AggregatedMetrics()
    ) {
        self.sourceType = sourceType
        self.sourceURL = sourceURL
        self.sourceAttribution = sourceAttribution
        self.rootProvenanceHash = rootProvenanceHash ?? Self.generateProvenanceHash()
        self.generation = generation
        self.parentShareID = parentShareID
        self.sharedByName = sharedByName
        self.createdAt = createdAt
        self.cloudKitRecordID = cloudKitRecordID
        self.lastSyncedAt = lastSyncedAt
        self.cachedMetrics = cachedMetrics
    }

    // MARK: - Helper Methods

    /// Generate a unique provenance hash for a new original recipe
    private static func generateProvenanceHash() -> String {
        let timestamp = Date().timeIntervalSince1970
        let random = UUID().uuidString
        let combined = "\(timestamp)-\(random)"
        return combined.sha256Hash()
    }

    /// Whether this recipe is an original (not shared from someone)
    var isOriginal: Bool {
        generation == 0
    }

    /// Whether this recipe was received via share
    var isShared: Bool {
        generation > 0
    }

    /// Display-friendly source description
    var displaySource: String {
        if let sharedBy = sharedByName, isShared {
            return "Shared by \(sharedBy)"
        }

        if let attribution = sourceAttribution {
            return attribution
        }

        switch sourceType {
        case .userCreated:
            return Recipe.currentUserDisplayName()
        case .imported:
            return sourceURL?.extractDomain() ?? "Imported"
        case .shared:
            return "Shared Recipe"
        case .scanned:
            return "Scanned"
        case .ai:
            return "AI Generated"
        case .video:
            return "Video Import"
        }
    }

    /// Badge text for generation indicator
    var generationBadgeText: String? {
        guard generation > 0 else { return nil }
        return "Gen \(generation)"
    }
}

// MARK: - Supporting Types

extension ProvenanceMetadata {
    enum SourceType: String, Codable, CaseIterable {
        case userCreated = "userCreated"    // Manually entered by user
        case imported = "imported"          // Imported from web URL
        case shared = "shared"              // Received via CKShare
        case scanned = "scanned"            // OCR from cookbook/card
        case ai = "ai"                      // Generated by AI
        case video = "video"                // Video import (YouTube, TikTok, camera roll)

        var displayName: String {
            switch self {
            case .userCreated: return "User Created"
            case .imported: return "Imported"
            case .shared: return "Shared"
            case .scanned: return "Scanned"
            case .ai: return "AI Generated"
            case .video: return "Video Import"
            }
        }

        var iconName: String {
            switch self {
            case .userCreated: return "pencil.circle.fill"
            case .imported: return "arrow.down.circle.fill"
            case .shared: return "person.2.fill"
            case .scanned: return "doc.text.viewfinder"
            case .ai: return "sparkles"
            case .video: return "video.circle.fill"
            }
        }
    }
}

/// Aggregated metrics cached from CloudKit public database
struct AggregatedMetrics: Codable, Hashable {
    /// Total number of times this recipe has been shared
    var totalShares: Int = 0

    /// Total number of times cooked across all users
    var totalCooks: Int = 0

    /// Average rating across all users (1-5)
    var averageRating: Double? = nil

    /// Number of users who rated
    var ratingCount: Int = 0

    /// Total number of comments across all copies
    var commentCount: Int = 0

    /// Trending score (calculated by server)
    var trendingScore: Double = 0.0

    /// Last time metrics were refreshed from CloudKit
    var lastUpdated: Date?

    /// Whether this recipe is currently trending
    var isTrending: Bool {
        trendingScore > 10.0 && totalShares > 5
    }

    /// Display-friendly share count
    var displayShareCount: String {
        if totalShares == 0 { return "" }
        if totalShares == 1 { return "1 share" }
        if totalShares < 100 { return "\(totalShares) shares" }
        return "100+ shares"
    }
}

// MARK: - String Extensions

extension String {
    /// Simple SHA256 hash (for provenance hash generation)
    func sha256Hash() -> String {
        guard let data = self.data(using: .utf8) else { return self }

        // Using CryptoKit for iOS 13+
        let hashed = SHA256.hash(data: data)
        return hashed.compactMap { String(format: "%02x", $0) }.joined()
    }

    /// Extract domain from URL string
    func extractDomain() -> String? {
        guard let url = URL(string: self),
              let host = url.host else { return nil }

        // Remove www. prefix
        let domain = host.replacingOccurrences(of: "^www\\.", with: "", options: .regularExpression)

        // Capitalize first letter
        return domain.prefix(1).uppercased() + domain.dropFirst()
    }
}

// MARK: - Sample Data

extension ProvenanceMetadata {
    /// Sample provenance for a user-created recipe
    static func sampleUserCreated() -> ProvenanceMetadata {
        ProvenanceMetadata(
            sourceType: .userCreated,
            sourceAttribution: "My Recipe",
            generation: 0
        )
    }

    /// Sample provenance for an imported recipe
    static func sampleImported() -> ProvenanceMetadata {
        ProvenanceMetadata(
            sourceType: .imported,
            sourceURL: "https://www.allrecipes.com/recipe/12345/chocolate-chip-cookies",
            sourceAttribution: "AllRecipes.com",
            generation: 0,
            cachedMetrics: AggregatedMetrics(
                totalShares: 15,
                totalCooks: 42,
                averageRating: 4.5,
                ratingCount: 12
            )
        )
    }

    /// Sample provenance for a shared recipe
    static func sampleShared() -> ProvenanceMetadata {
        ProvenanceMetadata(
            sourceType: .shared,
            sourceAttribution: "Originally from AllRecipes.com",
            generation: 1,
            parentShareID: "share-12345",
            sharedByName: "Sarah M.",
            cachedMetrics: AggregatedMetrics(
                totalShares: 3,
                totalCooks: 8,
                averageRating: 5.0,
                ratingCount: 2
            )
        )
    }
}
