/**
 * Seed data for demo creators and their public recipes
 * Full recipe content for Discovery feature captures
 */

// ============================================================================
// Types
// ============================================================================

export interface DemoCreator {
  id: string;
  creatorName: string;
  creatorProfileSlug: string;
  avatarDescription: string; // Used for image generation prompt
}

export interface SeedRecipe {
  id: string;
  sourceRecipeId: string;
  creatorId: string;
  creatorName: string;
  creatorProfileSlug: string;
  title: string;
  description: string;
  ingredients: string[];
  instructions: string[];
  category: string;
  tags: string[];
  servings: string;
  prepTime: string;
  cookTime: string;
  totalTime?: string;
  viewCount: number;
  saveCount: number;
  publishedDaysAgo: number;
}

// ============================================================================
// Demo Creators
// ============================================================================

export const DEMO_CREATORS: DemoCreator[] = [
  {
    id: 'demo_grandmazing',
    creatorName: 'Grandmazing',
    creatorProfileSlug: 'grandmazing',
    avatarDescription:
      'a warm friendly grandmother in her 60s with silver hair and a gentle smile, wearing a comfortable apron',
  },
  {
    id: 'demo_phillipfry',
    creatorName: 'Phillip Fry',
    creatorProfileSlug: 'phillip-fry',
    avatarDescription:
      'a young man in his late 20s with short brown hair, casual t-shirt, friendly approachable expression',
  },
  {
    id: 'demo_chef_maria',
    creatorName: 'Maria Santos',
    creatorProfileSlug: 'maria-santos',
    avatarDescription:
      'a professional Latina chef in her 40s with dark curly hair, wearing a white chef coat, confident warm smile',
  },
  {
    id: 'demo_fitfoodie',
    creatorName: 'Alex Chen',
    creatorProfileSlug: 'alex-chen',
    avatarDescription:
      'a fit Asian man in his early 30s with athletic build, wearing a tank top, energetic friendly expression',
  },
  {
    id: 'demo_bakingbelle',
    creatorName: 'Belle Thompson',
    creatorProfileSlug: 'belle-thompson',
    avatarDescription:
      'a young woman in her late 20s with blonde hair in a messy bun, flour on her apron, joyful creative expression',
  },
  {
    id: 'demo_grillmaster',
    creatorName: 'Marcus Johnson',
    creatorProfileSlug: 'marcus-johnson',
    avatarDescription:
      'a Black man in his 50s with a salt-and-pepper beard, wearing a BBQ apron, proud confident expression',
  },
];

// ============================================================================
// Grandmazing Recipes (7)
// ============================================================================

const GRANDMAZING_RECIPES: SeedRecipe[] = [
  {
    id: 'demo_grandmazing_lemon_garlic_chicken',
    sourceRecipeId: 'seed-uuid-001',
    creatorId: 'demo_grandmazing',
    creatorName: 'Grandmazing',
    creatorProfileSlug: 'grandmazing',
    title: 'Lemon Garlic Chicken',
    description:
      "This was my mother's Sunday dinner staple. The secret is marinating for at least two hours - the lemon tenderizes the chicken beautifully while the garlic infuses every bite. I've made this for three generations of my family now.",
    ingredients: [
      '4 bone-in chicken thighs',
      '3 tablespoons olive oil',
      '4 cloves garlic, minced',
      '2 lemons, juiced and zested',
      '1 tablespoon fresh rosemary, chopped',
      '1 teaspoon dried oregano',
      '1 teaspoon salt',
      '1/2 teaspoon black pepper',
      '1/4 cup chicken broth',
      '2 tablespoons butter',
      '1 tablespoon fresh parsley, chopped',
    ],
    instructions: [
      'In a bowl, combine olive oil, minced garlic, lemon juice, lemon zest, rosemary, oregano, salt, and pepper.',
      'Place chicken thighs in a large zip-lock bag and pour the marinade over them. Refrigerate for at least 2 hours, or overnight for best results.',
      'Preheat your oven to 425°F (220°C).',
      'Remove chicken from marinade and pat dry with paper towels. Reserve the marinade.',
      'Heat an oven-safe skillet over medium-high heat. Sear chicken skin-side down for 4-5 minutes until golden and crispy.',
      'Flip the chicken and pour the reserved marinade and chicken broth around the pieces.',
      'Transfer the skillet to the oven and roast for 25-30 minutes until the internal temperature reaches 165°F.',
      'Remove from oven, add butter to the pan, and baste the chicken with the pan juices.',
      'Let rest for 5 minutes, then garnish with fresh parsley and serve.',
    ],
    category: 'Dinner',
    tags: ['Chicken', 'Lemon', 'Garlic', 'Family Recipe', 'Sunday Dinner'],
    servings: '4 servings',
    prepTime: '15',
    cookTime: '35',
    totalTime: '50',
    viewCount: 3500,
    saveCount: 480,
    publishedDaysAgo: 14,
  },
  {
    id: 'demo_grandmazing_tomato_basil_soup',
    sourceRecipeId: 'seed-uuid-002',
    creatorId: 'demo_grandmazing',
    creatorName: 'Grandmazing',
    creatorProfileSlug: 'grandmazing',
    title: 'Cozy Tomato Basil Soup',
    description:
      "There's nothing like a warm bowl of tomato soup on a chilly day. I started making this when my kids were small and refused to eat their vegetables - they never knew this soup was packed with carrots and celery. It's been our family's comfort food ever since.",
    ingredients: [
      '2 cans (28 oz each) whole peeled tomatoes',
      '1 medium onion, diced',
      '2 carrots, peeled and chopped',
      '2 celery stalks, chopped',
      '4 cloves garlic, minced',
      '3 tablespoons olive oil',
      '4 cups vegetable broth',
      '1/2 cup fresh basil leaves, plus more for garnish',
      '1/2 cup heavy cream',
      '1 teaspoon sugar',
      '1 teaspoon salt',
      '1/2 teaspoon black pepper',
      '1/4 teaspoon red pepper flakes',
    ],
    instructions: [
      'Heat olive oil in a large Dutch oven over medium heat. Add onion, carrots, and celery. Cook for 8-10 minutes until softened.',
      'Add garlic and cook for another minute until fragrant.',
      'Pour in the canned tomatoes with their juices and the vegetable broth. Bring to a simmer.',
      'Add sugar, salt, pepper, and red pepper flakes. Simmer uncovered for 25-30 minutes.',
      'Remove from heat and add fresh basil leaves.',
      'Using an immersion blender, puree the soup until smooth. Alternatively, blend in batches in a regular blender.',
      'Stir in the heavy cream and heat through for 2-3 minutes.',
      'Taste and adjust seasonings as needed.',
      'Serve hot, garnished with fresh basil leaves and a drizzle of olive oil.',
    ],
    category: 'Soup',
    tags: ['Soup', 'Tomato', 'Comfort Food', 'Vegetarian', 'Kid-Friendly'],
    servings: '6 servings',
    prepTime: '15',
    cookTime: '40',
    totalTime: '55',
    viewCount: 1200,
    saveCount: 180,
    publishedDaysAgo: 30,
  },
  {
    id: 'demo_grandmazing_salmon_rice_bowls',
    sourceRecipeId: 'seed-uuid-003',
    creatorId: 'demo_grandmazing',
    creatorName: 'Grandmazing',
    creatorProfileSlug: 'grandmazing',
    title: 'Crispy Salmon Rice Bowls',
    description:
      "My granddaughter taught me this one! She came home from college talking about 'salmon rice' from the internet, so we worked on this version together. The crispy rice on the bottom is the best part - don't skip that step!",
    ingredients: [
      '2 salmon fillets (6 oz each)',
      '2 cups cooked jasmine rice, day-old works best',
      '3 tablespoons soy sauce',
      '1 tablespoon rice vinegar',
      '1 tablespoon sesame oil',
      '1 tablespoon sriracha mayo',
      '2 tablespoons vegetable oil',
      '1 avocado, sliced',
      '2 green onions, sliced',
      '1 tablespoon sesame seeds',
      '1 sheet nori, cut into strips',
      'Pickled ginger for serving',
    ],
    instructions: [
      'Season salmon fillets with salt and pepper. Heat 1 tablespoon vegetable oil in a non-stick pan over medium-high heat.',
      'Cook salmon skin-side up for 4 minutes, then flip and cook 3-4 more minutes until cooked through. Set aside.',
      'In the same pan, add remaining oil. Press day-old rice into the pan in an even layer.',
      'Let rice cook undisturbed for 5-6 minutes until bottom is golden and crispy.',
      'While rice crisps, mix soy sauce, rice vinegar, and sesame oil in a small bowl.',
      'Break salmon into large flakes, removing skin if desired.',
      'Flip the crispy rice onto a plate, crispy-side up. Top with salmon flakes.',
      'Drizzle with the soy sauce mixture and sriracha mayo.',
      'Add sliced avocado, green onions, sesame seeds, and nori strips. Serve with pickled ginger.',
    ],
    category: 'Dinner',
    tags: ['Salmon', 'Rice Bowl', 'Asian-Inspired', 'Quick Dinner', 'Crispy Rice'],
    servings: '2 servings',
    prepTime: '10',
    cookTime: '20',
    totalTime: '30',
    viewCount: 4200,
    saveCount: 620,
    publishedDaysAgo: 5,
  },
  {
    id: 'demo_grandmazing_chocolate_chip_cookies',
    sourceRecipeId: 'seed-uuid-004',
    creatorId: 'demo_grandmazing',
    creatorName: 'Grandmazing',
    creatorProfileSlug: 'grandmazing',
    title: 'Brown Butter Chocolate Chip Cookies',
    description:
      "I've been making chocolate chip cookies for over 50 years, but browning the butter was a game-changer I discovered just five years ago. The nutty, caramel notes make these absolutely irresistible. My grandkids say these are better than any bakery.",
    ingredients: [
      '1 cup (2 sticks) unsalted butter',
      '2 1/4 cups all-purpose flour',
      '1 teaspoon baking soda',
      '1 teaspoon salt',
      '1 cup packed brown sugar',
      '1/2 cup granulated sugar',
      '2 large eggs',
      '2 teaspoons vanilla extract',
      '2 cups semi-sweet chocolate chips',
      '1 cup chopped walnuts (optional)',
      'Flaky sea salt for topping',
    ],
    instructions: [
      'In a light-colored saucepan, melt butter over medium heat. Continue cooking, swirling occasionally, until butter turns golden brown and smells nutty, about 5-7 minutes. Pour into a heat-proof bowl and refrigerate until solid but still soft, about 1 hour.',
      'Whisk together flour, baking soda, and salt in a medium bowl.',
      'Using a mixer, beat the cooled brown butter with both sugars until light and fluffy, about 3 minutes.',
      'Beat in eggs one at a time, then add vanilla extract.',
      'Gradually mix in the flour mixture until just combined.',
      'Fold in chocolate chips and walnuts if using.',
      'Cover dough and refrigerate for at least 30 minutes (or up to 3 days).',
      'Preheat oven to 375°F. Line baking sheets with parchment paper.',
      'Scoop 2-tablespoon portions of dough onto prepared sheets, spacing 2 inches apart.',
      'Bake for 10-12 minutes until edges are golden but centers look slightly underdone.',
      'Sprinkle with flaky sea salt immediately. Cool on pan for 5 minutes before transferring.',
    ],
    category: 'Dessert',
    tags: ['Cookies', 'Chocolate', 'Brown Butter', 'Baking', 'Family Favorite'],
    servings: '36 cookies',
    prepTime: '20',
    cookTime: '12',
    totalTime: '32',
    viewCount: 1800,
    saveCount: 250,
    publishedDaysAgo: 14,
  },
  {
    id: 'demo_grandmazing_peanut_noodles',
    sourceRecipeId: 'seed-uuid-005',
    creatorId: 'demo_grandmazing',
    creatorName: 'Grandmazing',
    creatorProfileSlug: 'grandmazing',
    title: '15-Minute Spicy Peanut Noodles',
    description:
      "When my grandkids come over hungry and I don't have much time, these noodles save the day. The sauce comes together while the pasta cooks - true 15-minute magic. They always ask for seconds.",
    ingredients: [
      '8 oz linguine or spaghetti',
      '1/2 cup creamy peanut butter',
      '3 tablespoons soy sauce',
      '2 tablespoons rice vinegar',
      '1 tablespoon sesame oil',
      '1 tablespoon honey',
      '1 tablespoon sriracha (adjust to taste)',
      '2 cloves garlic, minced',
      '1/4 cup warm water',
      '2 cups shredded rotisserie chicken (optional)',
      '1 cup shredded carrots',
      '1/2 cup chopped cilantro',
      '1/4 cup chopped peanuts',
      'Lime wedges for serving',
    ],
    instructions: [
      'Bring a large pot of salted water to boil. Cook pasta according to package directions. Reserve 1/2 cup pasta water before draining.',
      'While pasta cooks, whisk together peanut butter, soy sauce, rice vinegar, sesame oil, honey, sriracha, and garlic in a large bowl.',
      'Add warm water gradually to thin the sauce to your desired consistency.',
      'Drain pasta and add to the bowl with the peanut sauce. Toss to coat completely.',
      'Add shredded chicken if using and toss again.',
      'If sauce is too thick, add reserved pasta water a little at a time.',
      'Divide among bowls and top with shredded carrots, cilantro, and chopped peanuts.',
      'Serve with lime wedges for squeezing over the top.',
    ],
    category: 'Dinner',
    tags: ['Noodles', 'Peanut', 'Quick Meal', '15-Minute', 'Kid-Friendly'],
    servings: '4 servings',
    prepTime: '5',
    cookTime: '10',
    totalTime: '15',
    viewCount: 380,
    saveCount: 52,
    publishedDaysAgo: 2,
  },
  {
    id: 'demo_grandmazing_sheet_pan_veggies',
    sourceRecipeId: 'seed-uuid-006',
    creatorId: 'demo_grandmazing',
    creatorName: 'Grandmazing',
    creatorProfileSlug: 'grandmazing',
    title: 'Sheet-Pan Roasted Vegetables',
    description:
      "I make these at least twice a week. The high heat caramelizes everything beautifully, and the herbs make the whole kitchen smell wonderful. My secret is not overcrowding the pan - give those vegetables room to breathe!",
    ingredients: [
      '2 medium zucchini, cut into half-moons',
      '1 red bell pepper, cut into chunks',
      '1 yellow bell pepper, cut into chunks',
      '1 red onion, cut into wedges',
      '8 oz cremini mushrooms, halved',
      '2 cups broccoli florets',
      '4 tablespoons olive oil',
      '4 cloves garlic, minced',
      '1 tablespoon fresh thyme leaves',
      '1 teaspoon dried Italian seasoning',
      '1 teaspoon salt',
      '1/2 teaspoon black pepper',
      '2 tablespoons balsamic glaze',
      '1/4 cup fresh parsley, chopped',
    ],
    instructions: [
      'Preheat oven to 425°F (220°C). Line two large baking sheets with parchment paper.',
      'In a very large bowl, combine all the cut vegetables.',
      'Drizzle with olive oil and add garlic, thyme, Italian seasoning, salt, and pepper. Toss until everything is evenly coated.',
      'Spread vegetables in a single layer across both baking sheets - don\'t overcrowd!',
      'Roast for 20 minutes, then rotate pans and flip vegetables.',
      'Continue roasting for another 15-20 minutes until vegetables are tender and caramelized at the edges.',
      'Transfer to a serving platter.',
      'Drizzle with balsamic glaze and sprinkle with fresh parsley.',
    ],
    category: 'Side Dish',
    tags: ['Vegetables', 'Roasted', 'Sheet Pan', 'Healthy', 'Vegan'],
    servings: '6 servings',
    prepTime: '15',
    cookTime: '40',
    totalTime: '55',
    viewCount: 950,
    saveCount: 140,
    publishedDaysAgo: 30,
  },
  {
    id: 'demo_grandmazing_steak_bites',
    sourceRecipeId: 'seed-uuid-007',
    creatorId: 'demo_grandmazing',
    creatorName: 'Grandmazing',
    creatorProfileSlug: 'grandmazing',
    title: 'Garlic Butter Steak Bites',
    description:
      "My husband requests these every Friday night. The key is getting your pan screaming hot and not moving the steak around too much. Those caramelized edges are pure gold, and the garlic butter at the end ties it all together.",
    ingredients: [
      '1.5 lbs sirloin steak, cut into 1-inch cubes',
      '4 tablespoons butter, divided',
      '2 tablespoons olive oil',
      '6 cloves garlic, minced',
      '1 tablespoon fresh rosemary, chopped',
      '1 tablespoon fresh thyme leaves',
      '1 teaspoon salt',
      '1 teaspoon black pepper',
      '1/2 teaspoon smoked paprika',
      '2 tablespoons fresh parsley, chopped',
    ],
    instructions: [
      'Pat steak cubes completely dry with paper towels. Season generously with salt, pepper, and smoked paprika.',
      'Heat a large cast-iron skillet over high heat until smoking hot.',
      'Add olive oil and 1 tablespoon butter to the pan.',
      'Working in batches to avoid crowding, add steak cubes in a single layer. Let them sear undisturbed for 2 minutes.',
      'Flip and sear another 1-2 minutes for medium-rare. Transfer to a plate.',
      'Reduce heat to medium. Add remaining butter, garlic, rosemary, and thyme.',
      'Cook for 30 seconds until garlic is fragrant but not browned.',
      'Return steak bites to the pan and toss to coat in the garlic butter.',
      'Garnish with fresh parsley and serve immediately.',
    ],
    category: 'Dinner',
    tags: ['Steak', 'Garlic', 'Quick Dinner', 'Cast Iron', 'Date Night'],
    servings: '4 servings',
    prepTime: '10',
    cookTime: '10',
    totalTime: '20',
    viewCount: 220,
    saveCount: 35,
    publishedDaysAgo: 2,
  },
];

// ============================================================================
// Phillip Fry Recipes (5)
// ============================================================================

const PHILLIP_FRY_RECIPES: SeedRecipe[] = [
  {
    id: 'demo_phillipfry_one_pot_pasta',
    sourceRecipeId: 'seed-uuid-008',
    creatorId: 'demo_phillipfry',
    creatorName: 'Phillip Fry',
    creatorProfileSlug: 'phillip-fry',
    title: 'Creamy One-Pot Pasta',
    description:
      "This is my go-to weeknight dinner. Everything cooks in one pot - pasta, sauce, everything. The starchy pasta water creates the creamiest sauce without any heavy cream. Plus, minimal dishes to wash. What's not to love?",
    ingredients: [
      '1 lb penne pasta',
      '4 cups chicken broth',
      '2 cups water',
      '1 can (14 oz) diced tomatoes',
      '1 medium onion, thinly sliced',
      '4 cloves garlic, sliced',
      '2 tablespoons olive oil',
      '1 teaspoon dried basil',
      '1/2 teaspoon red pepper flakes',
      '1 teaspoon salt',
      '1 cup fresh spinach',
      '1/2 cup parmesan cheese, grated',
      '1/4 cup fresh basil, torn',
    ],
    instructions: [
      'Combine pasta, chicken broth, water, diced tomatoes, onion, garlic, olive oil, dried basil, red pepper flakes, and salt in a large pot.',
      'Bring to a boil over high heat, stirring occasionally.',
      'Reduce heat to medium and maintain a steady simmer.',
      'Cook for 10-12 minutes, stirring every few minutes, until pasta is al dente and most liquid is absorbed.',
      'The mixture should be saucy but not soupy. If too dry, add a splash of water.',
      'Remove from heat and stir in fresh spinach until wilted.',
      'Add parmesan cheese and stir until melted and creamy.',
      'Taste and adjust seasoning as needed.',
      'Serve topped with fresh torn basil and extra parmesan.',
    ],
    category: 'Dinner',
    tags: ['Pasta', 'One-Pot', 'Weeknight Dinner', 'Easy', 'Vegetarian'],
    servings: '4-6 servings',
    prepTime: '5',
    cookTime: '15',
    totalTime: '20',
    viewCount: 3800,
    saveCount: 550,
    publishedDaysAgo: 5,
  },
  {
    id: 'demo_phillipfry_smashed_potatoes',
    sourceRecipeId: 'seed-uuid-009',
    creatorId: 'demo_phillipfry',
    creatorName: 'Phillip Fry',
    creatorProfileSlug: 'phillip-fry',
    title: 'Crispy Smashed Potatoes',
    description:
      "I learned this technique watching cooking videos at 2am and it changed my potato game forever. Boil, smash, roast. That's it. The edges get impossibly crispy while the insides stay fluffy. Perfect for any meal.",
    ingredients: [
      '2 lbs baby gold potatoes',
      '4 tablespoons olive oil',
      '4 tablespoons butter, melted',
      '4 cloves garlic, minced',
      '1 teaspoon salt',
      '1/2 teaspoon black pepper',
      '1/2 teaspoon garlic powder',
      '1/4 cup parmesan cheese, grated',
      '2 tablespoons fresh chives, chopped',
      '2 tablespoons fresh parsley, chopped',
      'Sour cream for serving',
    ],
    instructions: [
      'Place potatoes in a large pot, cover with cold salted water. Bring to a boil and cook until fork-tender, about 15-20 minutes.',
      'Preheat oven to 450°F (230°C). Line a baking sheet with parchment paper.',
      'Drain potatoes and arrange on the baking sheet.',
      'Using a fork or the bottom of a glass, gently press down on each potato to flatten to about 1/2 inch thick.',
      'Mix olive oil, melted butter, and minced garlic. Brush generously over each smashed potato.',
      'Season with salt, pepper, and garlic powder.',
      'Roast for 25-30 minutes until edges are golden brown and crispy.',
      'Sprinkle with parmesan cheese and return to oven for 5 more minutes.',
      'Top with fresh chives and parsley. Serve with sour cream.',
    ],
    category: 'Side Dish',
    tags: ['Potatoes', 'Crispy', 'Side Dish', 'Comfort Food', 'Vegetarian'],
    servings: '4 servings',
    prepTime: '10',
    cookTime: '50',
    totalTime: '60',
    viewCount: 1400,
    saveCount: 200,
    publishedDaysAgo: 14,
  },
  {
    id: 'demo_phillipfry_chickpea_salad',
    sourceRecipeId: 'seed-uuid-010',
    creatorId: 'demo_phillipfry',
    creatorName: 'Phillip Fry',
    creatorProfileSlug: 'phillip-fry',
    title: 'Lemony Chickpea Salad',
    description:
      "I started meal-prepping this when I was trying to eat healthier. It keeps in the fridge for days and actually tastes better after the flavors meld together. Great on its own, in a wrap, or on top of greens.",
    ingredients: [
      '2 cans (15 oz each) chickpeas, drained and rinsed',
      '1 cucumber, diced',
      '1 cup cherry tomatoes, halved',
      '1/2 red onion, finely diced',
      '1/2 cup kalamata olives, halved',
      '1/2 cup feta cheese, crumbled',
      '1/4 cup fresh parsley, chopped',
      '3 tablespoons olive oil',
      '2 tablespoons lemon juice',
      '1 clove garlic, minced',
      '1 teaspoon dried oregano',
      '1/2 teaspoon salt',
      '1/4 teaspoon black pepper',
    ],
    instructions: [
      'In a large bowl, combine chickpeas, cucumber, tomatoes, red onion, and olives.',
      'In a small bowl, whisk together olive oil, lemon juice, garlic, oregano, salt, and pepper.',
      'Pour dressing over the chickpea mixture and toss to combine.',
      'Add feta cheese and parsley, tossing gently.',
      'Taste and adjust seasoning as needed - it might need more lemon or salt.',
      'For best flavor, refrigerate for at least 30 minutes before serving.',
      'Can be stored in the fridge for up to 5 days.',
    ],
    category: 'Lunch',
    tags: ['Salad', 'Chickpeas', 'Meal Prep', 'Mediterranean', 'Vegetarian'],
    servings: '4 servings',
    prepTime: '15',
    cookTime: '0',
    totalTime: '15',
    viewCount: 180,
    saveCount: 28,
    publishedDaysAgo: 2,
  },
  {
    id: 'demo_phillipfry_pantry_chili',
    sourceRecipeId: 'seed-uuid-011',
    creatorId: 'demo_phillipfry',
    creatorName: 'Phillip Fry',
    creatorProfileSlug: 'phillip-fry',
    title: 'Quick Pantry Chili',
    description:
      "Made this for the first time when I had basically nothing in my fridge but a well-stocked pantry. Turns out canned goods can make an incredible chili. Now it's my game day staple.",
    ingredients: [
      '1 lb ground beef',
      '1 can (28 oz) crushed tomatoes',
      '1 can (15 oz) kidney beans, drained',
      '1 can (15 oz) black beans, drained',
      '1 can (15 oz) corn, drained',
      '1 medium onion, diced',
      '3 cloves garlic, minced',
      '2 tablespoons chili powder',
      '1 tablespoon cumin',
      '1 teaspoon smoked paprika',
      '1 teaspoon salt',
      '1/2 teaspoon black pepper',
      '1 cup beef broth',
      'Shredded cheese, sour cream, green onions for topping',
    ],
    instructions: [
      'In a large pot or Dutch oven, brown ground beef over medium-high heat, breaking it into crumbles. Drain excess fat.',
      'Add onion and cook for 5 minutes until softened. Add garlic and cook 1 minute more.',
      'Stir in chili powder, cumin, smoked paprika, salt, and pepper. Cook for 30 seconds until fragrant.',
      'Add crushed tomatoes, kidney beans, black beans, corn, and beef broth.',
      'Bring to a boil, then reduce heat and simmer uncovered for 25-30 minutes, stirring occasionally.',
      'The chili should thicken as it simmers. Add more broth if it gets too thick.',
      'Taste and adjust seasonings.',
      'Serve hot with shredded cheese, sour cream, and green onions.',
    ],
    category: 'Dinner',
    tags: ['Chili', 'Beef', 'Pantry Meal', 'Game Day', 'Comfort Food'],
    servings: '6 servings',
    prepTime: '10',
    cookTime: '40',
    totalTime: '50',
    viewCount: 1100,
    saveCount: 160,
    publishedDaysAgo: 30,
  },
  {
    id: 'demo_phillipfry_breakfast_hash',
    sourceRecipeId: 'seed-uuid-012',
    creatorId: 'demo_phillipfry',
    creatorName: 'Phillip Fry',
    creatorProfileSlug: 'phillip-fry',
    title: 'Breakfast Sheet-Pan Hash',
    description:
      "Brunch for a crowd without standing over a stove? Yes please. Everything roasts on one pan while you make coffee and set the table. The runny egg yolks mixing with the crispy potatoes is absolutely perfect.",
    ingredients: [
      '1.5 lbs baby potatoes, quartered',
      '1 red bell pepper, diced',
      '1 green bell pepper, diced',
      '1 medium onion, diced',
      '8 oz breakfast sausage, crumbled (or sliced kielbasa)',
      '4 tablespoons olive oil',
      '1 teaspoon paprika',
      '1 teaspoon garlic powder',
      '1 teaspoon salt',
      '1/2 teaspoon black pepper',
      '4-6 large eggs',
      '1/4 cup fresh chives, chopped',
      'Hot sauce for serving',
    ],
    instructions: [
      'Preheat oven to 425°F (220°C). Line a large sheet pan with parchment paper.',
      'Toss potatoes with 2 tablespoons olive oil, paprika, garlic powder, salt, and pepper. Spread on the pan.',
      'Roast for 20 minutes until potatoes start to get tender.',
      'Remove pan and add bell peppers, onion, and sausage. Drizzle with remaining olive oil and toss everything together.',
      'Spread in an even layer and roast for another 15-20 minutes until vegetables are tender and sausage is cooked.',
      'Remove pan and create 4-6 wells in the hash. Crack an egg into each well.',
      'Season eggs with salt and pepper. Return to oven for 8-10 minutes until egg whites are set but yolks are still runny.',
      'Sprinkle with fresh chives and serve immediately with hot sauce.',
    ],
    category: 'Breakfast',
    tags: ['Breakfast', 'Sheet Pan', 'Eggs', 'Brunch', 'Meal Prep'],
    servings: '4-6 servings',
    prepTime: '15',
    cookTime: '50',
    totalTime: '65',
    viewCount: 320,
    saveCount: 45,
    publishedDaysAgo: 5,
  },
];

// ============================================================================
// Chef Maria Recipes (6) - Latin Cuisine & Seafood
// ============================================================================

const CHEF_MARIA_RECIPES: SeedRecipe[] = [
  {
    id: 'demo_chef_maria_cuban_black_beans',
    sourceRecipeId: 'seed-uuid-013',
    creatorId: 'demo_chef_maria',
    creatorName: 'Maria Santos',
    creatorProfileSlug: 'maria-santos',
    title: 'Authentic Cuban Black Beans',
    description:
      "This is my abuela's recipe that I've been making since I was a little girl. The secret is the sofrito - take your time with it, and these beans will transport you straight to Havana. Serve over white rice with fried plantains on the side.",
    ingredients: [
      '1 lb dried black beans, soaked overnight',
      '1 large green bell pepper, diced',
      '1 large onion, diced',
      '8 cloves garlic, minced',
      '1/4 cup olive oil',
      '2 bay leaves',
      '1 tablespoon cumin',
      '1 tablespoon oregano',
      '2 tablespoons white wine vinegar',
      '1 tablespoon sugar',
      '2 teaspoons salt',
      '1/2 teaspoon black pepper',
      '6 cups water or chicken broth',
    ],
    instructions: [
      'Drain soaked beans and set aside.',
      'Heat olive oil in a large Dutch oven over medium heat. Add onion and bell pepper, cook for 10 minutes until softened.',
      'Add garlic and cook for 2 minutes until fragrant.',
      'Add cumin and oregano, stir for 30 seconds.',
      'Add beans, bay leaves, and water or broth. Bring to a boil.',
      'Reduce heat, cover, and simmer for 1.5-2 hours until beans are tender.',
      'Remove 1 cup of beans, mash them, and return to pot (this thickens the broth).',
      'Add vinegar, sugar, salt, and pepper. Simmer uncovered for 15 minutes.',
      'Remove bay leaves. Taste and adjust seasoning.',
      'Serve over white rice with a drizzle of olive oil.',
    ],
    category: 'Dinner',
    tags: ['Cuban', 'Beans', 'Latin', 'Vegan', 'Traditional'],
    servings: '8 servings',
    prepTime: '20',
    cookTime: '120',
    totalTime: '140',
    viewCount: 2100,
    saveCount: 320,
    publishedDaysAgo: 10,
  },
  {
    id: 'demo_chef_maria_garlic_shrimp',
    sourceRecipeId: 'seed-uuid-014',
    creatorId: 'demo_chef_maria',
    creatorName: 'Maria Santos',
    creatorProfileSlug: 'maria-santos',
    title: 'Camarones al Ajillo (Garlic Shrimp)',
    description:
      "A classic Spanish-Cuban dish that never fails to impress. The shrimp swim in a pool of garlicky, slightly spicy olive oil that's perfect for dipping crusty bread. I make this when I want to feel like I'm dining by the sea in Miami.",
    ingredients: [
      '1.5 lbs large shrimp, peeled and deveined',
      '1/2 cup olive oil',
      '10 cloves garlic, thinly sliced',
      '1 teaspoon red pepper flakes',
      '1/4 cup dry white wine',
      '2 tablespoons fresh lemon juice',
      '1/4 cup fresh parsley, chopped',
      '1 teaspoon smoked paprika',
      '1 teaspoon salt',
      'Crusty bread for serving',
    ],
    instructions: [
      'Pat shrimp dry and season with salt and smoked paprika.',
      'Heat olive oil in a large skillet over medium heat.',
      'Add garlic slices and cook for 1-2 minutes until just golden (watch carefully!).',
      'Add red pepper flakes and stir for 30 seconds.',
      'Increase heat to high. Add shrimp in a single layer.',
      'Cook for 2 minutes per side until pink and curled.',
      'Add white wine and lemon juice, cook for 1 minute.',
      'Remove from heat, sprinkle with fresh parsley.',
      'Serve immediately in the skillet with crusty bread for dipping.',
    ],
    category: 'Dinner',
    tags: ['Shrimp', 'Seafood', 'Spanish', 'Quick', 'Date Night'],
    servings: '4 servings',
    prepTime: '10',
    cookTime: '10',
    totalTime: '20',
    viewCount: 3200,
    saveCount: 480,
    publishedDaysAgo: 5,
  },
  {
    id: 'demo_chef_maria_ropa_vieja',
    sourceRecipeId: 'seed-uuid-015',
    creatorId: 'demo_chef_maria',
    creatorName: 'Maria Santos',
    creatorProfileSlug: 'maria-santos',
    title: 'Ropa Vieja (Shredded Beef)',
    description:
      "Cuba's national dish! The name means 'old clothes' because the shredded beef looks like colorful rags. This is pure comfort food - the beef gets impossibly tender and absorbs all those amazing flavors. My family fights over the crispy edges.",
    ingredients: [
      '2.5 lbs flank steak',
      '1 large onion, sliced',
      '2 bell peppers (red and green), sliced',
      '6 cloves garlic, minced',
      '1 can (14 oz) crushed tomatoes',
      '1/2 cup dry white wine',
      '1/2 cup pimiento-stuffed olives',
      '2 tablespoons tomato paste',
      '2 teaspoons cumin',
      '1 teaspoon oregano',
      '2 bay leaves',
      '3 cups beef broth',
      '3 tablespoons olive oil',
      'Salt and pepper to taste',
    ],
    instructions: [
      'Season flank steak with salt, pepper, cumin, and oregano.',
      'In a Dutch oven, sear the steak in 2 tablespoons olive oil until browned on both sides. Remove and set aside.',
      'Add remaining oil, onion, and peppers. Cook for 8 minutes until softened.',
      'Add garlic and tomato paste, cook for 2 minutes.',
      'Add wine and scrape up any browned bits.',
      'Add crushed tomatoes, beef broth, and bay leaves. Return steak to pot.',
      'Bring to a boil, then reduce heat. Cover and simmer for 2.5-3 hours until fork-tender.',
      'Remove steak and shred with two forks. Return to pot.',
      'Add olives and simmer uncovered for 15 minutes to thicken.',
      'Serve over white rice with fried plantains.',
    ],
    category: 'Dinner',
    tags: ['Cuban', 'Beef', 'Slow-Cooked', 'Traditional', 'Comfort Food'],
    servings: '6 servings',
    prepTime: '20',
    cookTime: '180',
    totalTime: '200',
    viewCount: 1800,
    saveCount: 290,
    publishedDaysAgo: 20,
  },
  {
    id: 'demo_chef_maria_ceviche',
    sourceRecipeId: 'seed-uuid-016',
    creatorId: 'demo_chef_maria',
    creatorName: 'Maria Santos',
    creatorProfileSlug: 'maria-santos',
    title: 'Classic Peruvian Ceviche',
    description:
      "Fresh, bright, and absolutely addictive. The lime juice 'cooks' the fish to perfection. I learned this technique from a chef in Lima and it changed how I think about seafood. Use the freshest fish you can find - it makes all the difference.",
    ingredients: [
      '1 lb fresh sea bass or halibut, cut into 1/2-inch cubes',
      '1 cup fresh lime juice (about 10 limes)',
      '1/2 red onion, thinly sliced',
      '1 jalapeño, seeded and minced',
      '1/4 cup fresh cilantro, chopped',
      '1 teaspoon salt',
      '1/2 teaspoon black pepper',
      '1 clove garlic, minced',
      '1 sweet potato, boiled and sliced (for serving)',
      'Corn kernels for garnish',
      'Tortilla chips for serving',
    ],
    instructions: [
      'Place fish cubes in a glass bowl. Add lime juice, ensuring fish is fully covered.',
      'Refrigerate for 15-20 minutes (fish should turn opaque but stay tender).',
      'Meanwhile, soak red onion slices in ice water for 10 minutes to remove bite. Drain well.',
      'Drain most of the lime juice from fish, leaving about 2 tablespoons.',
      'Add onion, jalapeño, garlic, cilantro, salt, and pepper. Gently toss.',
      'Taste and adjust lime/salt as needed.',
      'Serve immediately on a bed of sweet potato slices.',
      'Garnish with corn kernels and serve with tortilla chips.',
    ],
    category: 'Appetizer',
    tags: ['Seafood', 'Peruvian', 'Fresh', 'No-Cook', 'Light'],
    servings: '4 servings',
    prepTime: '25',
    cookTime: '0',
    totalTime: '25',
    viewCount: 950,
    saveCount: 140,
    publishedDaysAgo: 8,
  },
  {
    id: 'demo_chef_maria_tres_leches',
    sourceRecipeId: 'seed-uuid-017',
    creatorId: 'demo_chef_maria',
    creatorName: 'Maria Santos',
    creatorProfileSlug: 'maria-santos',
    title: 'Tres Leches Cake',
    description:
      "The most decadent, moist cake you'll ever taste. Three milks soak into every bite - it's like a hug from your abuela. I make this for every birthday in my family. Don't skimp on the soaking time, that's where the magic happens.",
    ingredients: [
      '1 cup all-purpose flour',
      '1 1/2 teaspoons baking powder',
      '5 large eggs',
      '1 cup sugar',
      '1/3 cup whole milk',
      '1 teaspoon vanilla extract',
      '1 can (14 oz) sweetened condensed milk',
      '1 can (12 oz) evaporated milk',
      '1 cup heavy cream',
      '2 cups heavy whipping cream (for topping)',
      '3 tablespoons powdered sugar',
      'Ground cinnamon for garnish',
    ],
    instructions: [
      'Preheat oven to 350°F. Grease a 9x13 inch baking dish.',
      'Whisk flour and baking powder together.',
      'Beat eggs and sugar until pale and fluffy, about 5 minutes.',
      'Add milk and vanilla, mix until combined.',
      'Fold in flour mixture gently. Pour into prepared dish.',
      'Bake for 25-30 minutes until golden and a toothpick comes out clean.',
      'Let cake cool completely in the pan.',
      'Mix condensed milk, evaporated milk, and 1 cup heavy cream.',
      'Poke holes all over the cake with a fork. Pour milk mixture evenly over cake.',
      'Refrigerate for at least 4 hours, preferably overnight.',
      'Whip 2 cups cream with powdered sugar until stiff peaks form.',
      'Spread over cake, dust with cinnamon, and serve cold.',
    ],
    category: 'Dessert',
    tags: ['Cake', 'Latin', 'Mexican', 'Birthday', 'Celebration'],
    servings: '12 servings',
    prepTime: '20',
    cookTime: '30',
    totalTime: '290',
    viewCount: 4100,
    saveCount: 680,
    publishedDaysAgo: 15,
  },
  {
    id: 'demo_chef_maria_empanadas',
    sourceRecipeId: 'seed-uuid-018',
    creatorId: 'demo_chef_maria',
    creatorName: 'Maria Santos',
    creatorProfileSlug: 'maria-santos',
    title: 'Beef Empanadas',
    description:
      "These golden pockets of joy are worth every minute of prep. The filling is savory and slightly sweet with raisins - a classic Cuban touch. I make big batches and freeze them so I always have some ready for unexpected guests.",
    ingredients: [
      '3 cups all-purpose flour',
      '1 teaspoon salt',
      '1/2 cup cold butter, cubed',
      '1 egg',
      '1/2 cup ice water',
      '1 lb ground beef',
      '1 onion, finely diced',
      '2 cloves garlic, minced',
      '1/2 cup green olives, chopped',
      '1/4 cup raisins',
      '1 teaspoon cumin',
      '1 teaspoon paprika',
      '1 egg beaten (for egg wash)',
    ],
    instructions: [
      'Make dough: Mix flour and salt. Cut in butter until crumbly. Add egg and water, mix until dough forms. Refrigerate 1 hour.',
      'Make filling: Brown beef in a skillet, drain excess fat.',
      'Add onion and cook 5 minutes. Add garlic, cumin, and paprika.',
      'Stir in olives and raisins. Season with salt. Cool completely.',
      'Roll dough to 1/8 inch thick. Cut 5-inch circles.',
      'Place 2 tablespoons filling on each circle. Fold in half.',
      'Seal edges with a fork. Place on parchment-lined baking sheets.',
      'Brush with egg wash. Bake at 400°F for 20-25 minutes until golden.',
      'Serve warm with chimichurri sauce.',
    ],
    category: 'Appetizer',
    tags: ['Empanadas', 'Beef', 'Cuban', 'Party Food', 'Freezer-Friendly'],
    servings: '16 empanadas',
    prepTime: '45',
    cookTime: '25',
    totalTime: '130',
    viewCount: 2400,
    saveCount: 380,
    publishedDaysAgo: 25,
  },
];

// ============================================================================
// Alex Chen (FitFoodie) Recipes (6) - Healthy & High-Protein
// ============================================================================

const FITFOODIE_RECIPES: SeedRecipe[] = [
  {
    id: 'demo_fitfoodie_protein_bowl',
    sourceRecipeId: 'seed-uuid-019',
    creatorId: 'demo_fitfoodie',
    creatorName: 'Alex Chen',
    creatorProfileSlug: 'alex-chen',
    title: 'Ultimate Protein Power Bowl',
    description:
      "This is my go-to post-workout meal. 45g of protein in one delicious bowl! I prep the components on Sunday and assemble fresh bowls all week. The tahini dressing is what makes it addictive - I put it on everything.",
    ingredients: [
      '6 oz grilled chicken breast, sliced',
      '1 cup cooked quinoa',
      '1 cup roasted chickpeas',
      '2 cups mixed greens',
      '1/2 cup shredded red cabbage',
      '1/2 cucumber, diced',
      '1/4 cup cherry tomatoes, halved',
      '2 tablespoons tahini',
      '1 tablespoon lemon juice',
      '1 tablespoon olive oil',
      '1 clove garlic, minced',
      '2 tablespoons water',
      'Salt and pepper to taste',
      'Everything bagel seasoning for garnish',
    ],
    instructions: [
      'Make the dressing: Whisk tahini, lemon juice, olive oil, garlic, and water until smooth. Season with salt.',
      'Arrange quinoa in the bottom of a large bowl.',
      'Top with mixed greens, cabbage, cucumber, and tomatoes in sections.',
      'Add sliced chicken breast and roasted chickpeas.',
      'Drizzle generously with tahini dressing.',
      'Sprinkle with everything bagel seasoning.',
      'Serve immediately or pack for meal prep (keep dressing separate).',
    ],
    category: 'Lunch',
    tags: ['High-Protein', 'Meal Prep', 'Healthy', 'Bowl', 'Post-Workout'],
    servings: '1 serving',
    prepTime: '15',
    cookTime: '0',
    totalTime: '15',
    viewCount: 3800,
    saveCount: 620,
    publishedDaysAgo: 3,
  },
  {
    id: 'demo_fitfoodie_egg_muffins',
    sourceRecipeId: 'seed-uuid-020',
    creatorId: 'demo_fitfoodie',
    creatorName: 'Alex Chen',
    creatorProfileSlug: 'alex-chen',
    title: 'Veggie-Packed Egg Muffins',
    description:
      "Grab-and-go protein that makes mornings so much easier. I make a dozen on Sunday and have breakfast handled for the week. Feel free to switch up the veggies - these are super versatile and only 90 calories each with 7g protein.",
    ingredients: [
      '8 large eggs',
      '1/4 cup milk',
      '1 cup spinach, chopped',
      '1/2 red bell pepper, diced',
      '1/4 cup onion, diced',
      '1/4 cup feta cheese, crumbled',
      '1/2 teaspoon salt',
      '1/4 teaspoon black pepper',
      '1/4 teaspoon garlic powder',
      'Cooking spray',
    ],
    instructions: [
      'Preheat oven to 350°F. Spray a 12-cup muffin tin with cooking spray.',
      'Whisk eggs, milk, salt, pepper, and garlic powder in a large bowl.',
      'Divide spinach, bell pepper, and onion evenly among muffin cups.',
      'Pour egg mixture over vegetables, filling each cup 3/4 full.',
      'Top each with crumbled feta cheese.',
      'Bake for 20-22 minutes until eggs are set and slightly golden.',
      'Let cool for 5 minutes before removing from tin.',
      'Store in refrigerator for up to 5 days. Reheat in microwave for 30 seconds.',
    ],
    category: 'Breakfast',
    tags: ['Eggs', 'Meal Prep', 'Low-Carb', 'Keto', 'Grab-and-Go'],
    servings: '12 muffins',
    prepTime: '10',
    cookTime: '22',
    totalTime: '32',
    viewCount: 2200,
    saveCount: 380,
    publishedDaysAgo: 12,
  },
  {
    id: 'demo_fitfoodie_turkey_lettuce_wraps',
    sourceRecipeId: 'seed-uuid-021',
    creatorId: 'demo_fitfoodie',
    creatorName: 'Alex Chen',
    creatorProfileSlug: 'alex-chen',
    title: 'Asian Turkey Lettuce Wraps',
    description:
      "All the flavor of takeout with a fraction of the carbs. These are ready in 15 minutes and taste incredible. The water chestnuts add the best crunch. I make extra filling to have over cauliflower rice the next day.",
    ingredients: [
      '1 lb lean ground turkey',
      '1 tablespoon sesame oil',
      '3 cloves garlic, minced',
      '1 tablespoon fresh ginger, minced',
      '1 can (8 oz) water chestnuts, diced',
      '3 green onions, sliced',
      '3 tablespoons coconut aminos (or low-sodium soy sauce)',
      '1 tablespoon rice vinegar',
      '1 tablespoon sriracha',
      '1 head butter lettuce',
      'Sesame seeds for garnish',
      'Fresh cilantro for garnish',
    ],
    instructions: [
      'Heat sesame oil in a large skillet over medium-high heat.',
      'Add ground turkey, breaking it up as it cooks, for 5-6 minutes until browned.',
      'Add garlic and ginger, cook for 1 minute until fragrant.',
      'Stir in water chestnuts and half the green onions.',
      'Add coconut aminos, rice vinegar, and sriracha. Cook 2 minutes.',
      'Separate lettuce leaves to use as cups.',
      'Spoon turkey mixture into lettuce cups.',
      'Garnish with remaining green onions, sesame seeds, and cilantro.',
    ],
    category: 'Dinner',
    tags: ['Turkey', 'Low-Carb', 'Asian', 'Quick', 'Healthy'],
    servings: '4 servings',
    prepTime: '10',
    cookTime: '10',
    totalTime: '20',
    viewCount: 1600,
    saveCount: 240,
    publishedDaysAgo: 7,
  },
  {
    id: 'demo_fitfoodie_greek_yogurt_parfait',
    sourceRecipeId: 'seed-uuid-022',
    creatorId: 'demo_fitfoodie',
    creatorName: 'Alex Chen',
    creatorProfileSlug: 'alex-chen',
    title: 'Protein-Packed Greek Yogurt Parfait',
    description:
      "Dessert for breakfast? Yes please! This parfait has 35g of protein and tastes like a treat. I prep jars for the whole week - they're grab-and-go and so satisfying. The protein powder mixed into the yogurt is a game-changer.",
    ingredients: [
      '1 1/2 cups plain Greek yogurt',
      '1 scoop vanilla protein powder',
      '1 tablespoon honey',
      '1/2 cup mixed berries',
      '1/4 cup low-sugar granola',
      '1 tablespoon almond butter',
      '1 tablespoon chia seeds',
      'Pinch of cinnamon',
    ],
    instructions: [
      'In a bowl, mix Greek yogurt with protein powder until smooth.',
      'Add honey and cinnamon, stir to combine.',
      'In a jar or bowl, layer half the yogurt mixture.',
      'Add half the berries and half the granola.',
      'Repeat with remaining yogurt, berries, and granola.',
      'Drizzle with almond butter and sprinkle chia seeds on top.',
      'Serve immediately or refrigerate overnight for meal prep.',
    ],
    category: 'Breakfast',
    tags: ['Yogurt', 'High-Protein', 'Meal Prep', 'Quick', 'Healthy'],
    servings: '1 serving',
    prepTime: '5',
    cookTime: '0',
    totalTime: '5',
    viewCount: 1100,
    saveCount: 180,
    publishedDaysAgo: 4,
  },
  {
    id: 'demo_fitfoodie_salmon_sheet_pan',
    sourceRecipeId: 'seed-uuid-023',
    creatorId: 'demo_fitfoodie',
    creatorName: 'Alex Chen',
    creatorProfileSlug: 'alex-chen',
    title: 'Sheet Pan Salmon with Veggies',
    description:
      "One pan, minimal cleanup, maximum nutrition. This is my lazy healthy dinner that still looks impressive. The salmon gets perfectly flaky while the veggies roast to caramelized perfection. Omega-3s for the win!",
    ingredients: [
      '4 salmon fillets (6 oz each)',
      '2 cups broccoli florets',
      '1 cup cherry tomatoes',
      '1 zucchini, sliced',
      '3 tablespoons olive oil',
      '3 cloves garlic, minced',
      '1 lemon, sliced',
      '1 teaspoon dried dill',
      '1 teaspoon paprika',
      '1 teaspoon salt',
      '1/2 teaspoon black pepper',
    ],
    instructions: [
      'Preheat oven to 400°F. Line a large sheet pan with parchment paper.',
      'Toss broccoli, tomatoes, and zucchini with 2 tablespoons olive oil, salt, and pepper.',
      'Spread vegetables on the sheet pan, leaving space in the center.',
      'Place salmon fillets in the center. Brush with remaining olive oil.',
      'Season salmon with garlic, dill, paprika, salt, and pepper.',
      'Top each fillet with lemon slices.',
      'Bake for 15-18 minutes until salmon flakes easily and vegetables are tender.',
      'Serve immediately with a squeeze of fresh lemon.',
    ],
    category: 'Dinner',
    tags: ['Salmon', 'Sheet Pan', 'Healthy', 'Omega-3', 'Quick'],
    servings: '4 servings',
    prepTime: '10',
    cookTime: '18',
    totalTime: '28',
    viewCount: 2800,
    saveCount: 420,
    publishedDaysAgo: 10,
  },
  {
    id: 'demo_fitfoodie_overnight_oats',
    sourceRecipeId: 'seed-uuid-024',
    creatorId: 'demo_fitfoodie',
    creatorName: 'Alex Chen',
    creatorProfileSlug: 'alex-chen',
    title: 'Chocolate Peanut Butter Overnight Oats',
    description:
      "Tastes like a Reese's cup but it's actually good for you! I crave these in the morning. The combination of oats, protein, and healthy fats keeps me full until lunch. Make a batch of 5 jars for the whole work week.",
    ingredients: [
      '1/2 cup rolled oats',
      '1/2 cup unsweetened almond milk',
      '1/4 cup plain Greek yogurt',
      '1 scoop chocolate protein powder',
      '2 tablespoons natural peanut butter',
      '1 tablespoon cocoa powder',
      '1 tablespoon maple syrup',
      '1 tablespoon chia seeds',
      'Banana slices for topping',
      'Chopped peanuts for topping',
    ],
    instructions: [
      'In a jar or container, combine oats, almond milk, and Greek yogurt.',
      'Add protein powder, cocoa powder, and maple syrup. Stir well.',
      'Add chia seeds and stir again.',
      'Dollop peanut butter on top (it will swirl in as you eat).',
      'Cover and refrigerate overnight, or at least 4 hours.',
      'In the morning, top with banana slices and chopped peanuts.',
      'Eat cold or microwave for 1-2 minutes if you prefer warm oats.',
    ],
    category: 'Breakfast',
    tags: ['Oats', 'Meal Prep', 'High-Protein', 'Chocolate', 'No-Cook'],
    servings: '1 serving',
    prepTime: '5',
    cookTime: '0',
    totalTime: '5',
    viewCount: 1900,
    saveCount: 310,
    publishedDaysAgo: 6,
  },
];

// ============================================================================
// Belle Thompson (BakingBelle) Recipes (6) - Desserts & Pastries
// ============================================================================

const BAKINGBELLE_RECIPES: SeedRecipe[] = [
  {
    id: 'demo_bakingbelle_sourdough_cinnamon_rolls',
    sourceRecipeId: 'seed-uuid-025',
    creatorId: 'demo_bakingbelle',
    creatorName: 'Belle Thompson',
    creatorProfileSlug: 'belle-thompson',
    title: 'Sourdough Cinnamon Rolls',
    description:
      "These are the cinnamon rolls I'm most proud of. Using sourdough discard adds this subtle tang that makes the sweet filling pop. They take some planning, but your kitchen will smell like a bakery and your family will worship you.",
    ingredients: [
      '1 cup sourdough discard',
      '3/4 cup warm milk',
      '1/4 cup butter, melted',
      '1/4 cup sugar',
      '1 egg',
      '3 cups all-purpose flour',
      '1 teaspoon salt',
      '1/2 cup brown sugar',
      '2 tablespoons cinnamon',
      '1/4 cup butter, softened',
      '4 oz cream cheese, softened',
      '2 cups powdered sugar',
      '1/4 cup butter, softened',
      '1 teaspoon vanilla',
    ],
    instructions: [
      'Mix sourdough discard, warm milk, melted butter, sugar, and egg.',
      'Add flour and salt, knead until smooth and elastic, about 8 minutes.',
      'Cover and let rise for 2 hours (or refrigerate overnight).',
      'Roll dough into a 12x18 inch rectangle.',
      'Spread softened butter over dough. Mix brown sugar and cinnamon, sprinkle evenly.',
      'Roll up tightly from the long side. Cut into 12 rolls.',
      'Place in a greased 9x13 inch pan. Cover and let rise 1 hour.',
      'Bake at 375°F for 22-25 minutes until golden.',
      'Make frosting: Beat cream cheese, butter, powdered sugar, and vanilla until fluffy.',
      'Spread frosting over warm rolls. Serve immediately.',
    ],
    category: 'Breakfast',
    tags: ['Cinnamon Rolls', 'Sourdough', 'Baking', 'Brunch', 'Special Occasion'],
    servings: '12 rolls',
    prepTime: '30',
    cookTime: '25',
    totalTime: '195',
    viewCount: 5200,
    saveCount: 890,
    publishedDaysAgo: 8,
  },
  {
    id: 'demo_bakingbelle_lemon_tart',
    sourceRecipeId: 'seed-uuid-026',
    creatorId: 'demo_bakingbelle',
    creatorName: 'Belle Thompson',
    creatorProfileSlug: 'belle-thompson',
    title: 'Classic French Lemon Tart',
    description:
      "Buttery crust, silky lemon curd, and that perfect balance of sweet and tart. This is the dessert that made me fall in love with French pastry. It looks impressive but is totally doable - just don't skip the blind baking step!",
    ingredients: [
      '1 1/4 cups all-purpose flour',
      '1/2 cup powdered sugar',
      '1/4 teaspoon salt',
      '1/2 cup cold butter, cubed',
      '1 egg yolk',
      '4 large eggs',
      '1 cup sugar',
      '2/3 cup fresh lemon juice',
      '1 tablespoon lemon zest',
      '1/2 cup heavy cream',
      '4 tablespoons butter, cubed',
      'Powdered sugar for dusting',
    ],
    instructions: [
      'Make crust: Pulse flour, powdered sugar, salt, and butter in food processor until crumbly.',
      'Add egg yolk, pulse until dough forms. Press into 9-inch tart pan. Refrigerate 30 minutes.',
      'Blind bake: Line crust with parchment and pie weights. Bake at 375°F for 15 minutes.',
      'Remove weights, bake 10 more minutes until golden. Let cool.',
      'Make curd: Whisk eggs, sugar, lemon juice, and zest in a saucepan.',
      'Cook over medium heat, stirring constantly, until thickened (about 8-10 minutes).',
      'Remove from heat, stir in cream and butter until smooth.',
      'Strain curd through a fine mesh sieve into the cooled tart shell.',
      'Refrigerate for at least 2 hours until set.',
      'Dust with powdered sugar before serving.',
    ],
    category: 'Dessert',
    tags: ['Tart', 'Lemon', 'French', 'Elegant', 'Citrus'],
    servings: '8 servings',
    prepTime: '30',
    cookTime: '35',
    totalTime: '185',
    viewCount: 2900,
    saveCount: 480,
    publishedDaysAgo: 14,
  },
  {
    id: 'demo_bakingbelle_chocolate_lava_cakes',
    sourceRecipeId: 'seed-uuid-027',
    creatorId: 'demo_bakingbelle',
    creatorName: 'Belle Thompson',
    creatorProfileSlug: 'belle-thompson',
    title: 'Molten Chocolate Lava Cakes',
    description:
      "The moment you cut into one of these and see that gooey center flow out... pure magic. They seem fancy but are actually super easy - only 20 minutes start to finish. Perfect for impressing a date or treating yourself.",
    ingredients: [
      '4 oz bittersweet chocolate, chopped',
      '1/2 cup unsalted butter',
      '1 cup powdered sugar',
      '2 whole eggs',
      '2 egg yolks',
      '6 tablespoons all-purpose flour',
      '1/4 teaspoon salt',
      'Butter and cocoa for ramekins',
      'Vanilla ice cream for serving',
      'Fresh raspberries for garnish',
    ],
    instructions: [
      'Preheat oven to 425°F. Butter 4 ramekins and dust with cocoa powder.',
      'Melt chocolate and butter together in microwave in 30-second intervals, stirring.',
      'Whisk in powdered sugar until smooth.',
      'Add whole eggs and egg yolks, whisk until combined.',
      'Fold in flour and salt until just combined.',
      'Divide batter among ramekins.',
      'Bake for 12-14 minutes - edges should be firm but center jiggly.',
      'Let cool for 1 minute, then run a knife around edges.',
      'Invert onto plates. Serve immediately with ice cream and raspberries.',
    ],
    category: 'Dessert',
    tags: ['Chocolate', 'Lava Cake', 'Date Night', 'Quick', 'Impressive'],
    servings: '4 cakes',
    prepTime: '10',
    cookTime: '14',
    totalTime: '24',
    viewCount: 4100,
    saveCount: 720,
    publishedDaysAgo: 5,
  },
  {
    id: 'demo_bakingbelle_macarons',
    sourceRecipeId: 'seed-uuid-028',
    creatorId: 'demo_bakingbelle',
    creatorName: 'Belle Thompson',
    creatorProfileSlug: 'belle-thompson',
    title: 'French Macarons',
    description:
      "Yes, macarons are finicky. Yes, they're worth it. After dozens of batches, I've figured out all the tricks. The key is aged egg whites and proper macaronage - that fold where the batter flows like lava. You've got this!",
    ingredients: [
      '1 cup almond flour, sifted',
      '1 3/4 cups powdered sugar, sifted',
      '3 large egg whites, room temperature and aged 24 hours',
      '1/4 cup granulated sugar',
      '1/4 teaspoon cream of tartar',
      'Gel food coloring (optional)',
      '1/2 cup butter, softened',
      '2 cups powdered sugar',
      '2 tablespoons heavy cream',
      '1 teaspoon vanilla extract',
    ],
    instructions: [
      'Sift almond flour and powdered sugar together twice. Set aside.',
      'Beat egg whites until foamy. Add cream of tartar.',
      'Gradually add granulated sugar, beat to stiff glossy peaks.',
      'Add food coloring if using.',
      'Fold in almond flour mixture in 3 additions - fold until batter flows like lava (macaronage).',
      'Pipe 1.5-inch circles on parchment-lined baking sheets.',
      'Tap pans firmly to release air bubbles. Let rest 30-60 minutes until dry to touch.',
      'Bake at 300°F for 15-17 minutes. Let cool completely.',
      'Make buttercream: Beat butter until fluffy, add powdered sugar, cream, and vanilla.',
      'Pipe filling on flat side of one shell, sandwich with another.',
      'Refrigerate 24 hours for best texture.',
    ],
    category: 'Dessert',
    tags: ['Macarons', 'French', 'Advanced', 'Elegant', 'Cookies'],
    servings: '24 macarons',
    prepTime: '45',
    cookTime: '17',
    totalTime: '120',
    viewCount: 3400,
    saveCount: 540,
    publishedDaysAgo: 20,
  },
  {
    id: 'demo_bakingbelle_apple_galette',
    sourceRecipeId: 'seed-uuid-029',
    creatorId: 'demo_bakingbelle',
    creatorName: 'Belle Thompson',
    creatorProfileSlug: 'belle-thompson',
    title: 'Rustic Apple Galette',
    description:
      "This is what I make when I want pie but don't want to fuss with a pie dish. It's deliberately imperfect and absolutely gorgeous. The rough edges get extra crispy and caramelized - my favorite part to steal before serving.",
    ingredients: [
      '1 1/4 cups all-purpose flour',
      '1/2 teaspoon salt',
      '1 tablespoon sugar',
      '1/2 cup cold butter, cubed',
      '4-6 tablespoons ice water',
      '4 medium apples, thinly sliced',
      '1/3 cup brown sugar',
      '1 teaspoon cinnamon',
      '1/4 teaspoon nutmeg',
      '1 tablespoon lemon juice',
      '2 tablespoons butter',
      '1 egg beaten with 1 tablespoon water',
      'Turbinado sugar for sprinkling',
    ],
    instructions: [
      'Make dough: Pulse flour, salt, and sugar in food processor. Add butter, pulse until pea-sized.',
      'Add ice water 1 tablespoon at a time until dough comes together.',
      'Form into a disk, wrap in plastic, refrigerate 1 hour.',
      'Toss apple slices with brown sugar, cinnamon, nutmeg, and lemon juice.',
      'Roll dough into a rough 12-inch circle on parchment paper.',
      'Arrange apples in center, leaving a 2-inch border.',
      'Dot apples with butter pieces.',
      'Fold edges over apples, pleating as you go. Brush crust with egg wash.',
      'Sprinkle crust with turbinado sugar.',
      'Bake at 400°F for 40-45 minutes until golden and bubbling.',
      'Serve warm with vanilla ice cream.',
    ],
    category: 'Dessert',
    tags: ['Apple', 'Galette', 'Pie', 'Fall', 'Rustic'],
    servings: '8 servings',
    prepTime: '25',
    cookTime: '45',
    totalTime: '130',
    viewCount: 2100,
    saveCount: 340,
    publishedDaysAgo: 12,
  },
  {
    id: 'demo_bakingbelle_croissants',
    sourceRecipeId: 'seed-uuid-030',
    creatorId: 'demo_bakingbelle',
    creatorName: 'Belle Thompson',
    creatorProfileSlug: 'belle-thompson',
    title: 'Homemade Croissants',
    description:
      "Making croissants from scratch is my meditation. Yes, it takes 2 days. Yes, it's totally worth it. When you see those flaky layers and taste that buttery perfection, you'll understand why French pastry chefs dedicate their lives to this craft.",
    ingredients: [
      '4 cups all-purpose flour',
      '1/3 cup sugar',
      '1 tablespoon salt',
      '1 tablespoon instant yeast',
      '1 1/4 cups cold milk',
      '1 1/2 cups cold European-style butter (for lamination)',
      '1 egg beaten with 1 tablespoon milk',
    ],
    instructions: [
      'Day 1: Mix flour, sugar, salt, and yeast. Add cold milk, mix until dough forms.',
      'Knead briefly, wrap in plastic, refrigerate overnight.',
      'Pound butter between parchment into a 6x8 inch rectangle. Keep cold.',
      'Day 2: Roll dough into a 12x8 inch rectangle. Place butter in center.',
      'Fold dough over butter like a letter. Roll to 8x18 inches.',
      'Fold into thirds. This is one turn. Refrigerate 1 hour.',
      'Repeat rolling and folding 2 more times, chilling between each.',
      'Roll final dough to 1/4 inch thick. Cut into triangles.',
      'Roll each triangle from base to tip. Curve ends into crescent shape.',
      'Let proof 2 hours until doubled and jiggly.',
      'Brush with egg wash. Bake at 400°F for 15-18 minutes until deep golden.',
    ],
    category: 'Breakfast',
    tags: ['Croissants', 'French', 'Advanced', 'Laminated Dough', 'Weekend Project'],
    servings: '12 croissants',
    prepTime: '60',
    cookTime: '18',
    totalTime: '1440',
    viewCount: 4800,
    saveCount: 780,
    publishedDaysAgo: 30,
  },
];

// ============================================================================
// Marcus Johnson (GrillMaster) Recipes (6) - BBQ & Grilling
// ============================================================================

const GRILLMASTER_RECIPES: SeedRecipe[] = [
  {
    id: 'demo_grillmaster_baby_back_ribs',
    sourceRecipeId: 'seed-uuid-031',
    creatorId: 'demo_grillmaster',
    creatorName: 'Marcus Johnson',
    creatorProfileSlug: 'marcus-johnson',
    title: 'Kansas City Baby Back Ribs',
    description:
      "Fall-off-the-bone tender with that perfect caramelized bark. This is my competition recipe that's won me three trophies. The secret is the 3-2-1 method and my special dry rub. Low and slow, my friends - that's the only way.",
    ingredients: [
      '2 racks baby back ribs (about 3 lbs each)',
      '1/4 cup brown sugar',
      '2 tablespoons paprika',
      '1 tablespoon garlic powder',
      '1 tablespoon onion powder',
      '1 tablespoon chili powder',
      '1 teaspoon cayenne pepper',
      '2 teaspoons salt',
      '1 teaspoon black pepper',
      '1/2 cup apple cider vinegar',
      '1/4 cup apple juice',
      '1 cup BBQ sauce',
      '4 tablespoons butter',
      '2 tablespoons honey',
    ],
    instructions: [
      'Remove membrane from back of ribs. Mix all dry spices to make the rub.',
      'Coat ribs generously with rub. Refrigerate 2 hours or overnight.',
      'Set up smoker or grill for indirect heat at 225°F. Add wood chips (hickory or apple).',
      '3-2-1 Method: Smoke ribs meat-side up for 3 hours, spritzing with vinegar/apple juice hourly.',
      'Wrap ribs in foil with butter, honey, and 2 tablespoons apple juice. Cook 2 hours.',
      'Unwrap ribs, brush with BBQ sauce. Cook 1 more hour until bark forms.',
      'Let rest 10 minutes before cutting between bones.',
      'Serve with extra sauce and plenty of napkins.',
    ],
    category: 'Dinner',
    tags: ['Ribs', 'BBQ', 'Smoked', 'Kansas City', 'Competition'],
    servings: '6 servings',
    prepTime: '30',
    cookTime: '360',
    totalTime: '390',
    viewCount: 4500,
    saveCount: 720,
    publishedDaysAgo: 7,
  },
  {
    id: 'demo_grillmaster_smash_burgers',
    sourceRecipeId: 'seed-uuid-032',
    creatorId: 'demo_grillmaster',
    creatorName: 'Marcus Johnson',
    creatorProfileSlug: 'marcus-johnson',
    title: 'Ultimate Smash Burgers',
    description:
      "Those crispy, lacy edges you get at the best burger joints? Now you can make them at home. The key is a screaming hot surface and smashing fast. Don't baby these burgers - they need aggressive heat and minimal flipping.",
    ingredients: [
      '1 lb ground beef (80/20 blend)',
      '4 slices American cheese',
      '4 brioche buns, toasted',
      'Salt and pepper',
      '2 tablespoons butter',
      'Special sauce:',
      '1/4 cup mayonnaise',
      '2 tablespoons ketchup',
      '1 tablespoon yellow mustard',
      '1 tablespoon pickle relish',
      'Toppings: lettuce, tomato, pickles, onion',
    ],
    instructions: [
      'Make special sauce: Mix mayo, ketchup, mustard, and relish. Refrigerate.',
      'Divide beef into 4 balls (about 4 oz each). Don\'t overwork the meat.',
      'Heat a cast iron skillet or griddle over high heat until smoking.',
      'Place beef balls on the hot surface. Immediately smash flat with a sturdy spatula.',
      'Season generously with salt and pepper. Cook 2-3 minutes until edges are crispy and brown.',
      'Flip burgers. Add cheese immediately. Cook 1 more minute.',
      'Toast buns in butter on the griddle.',
      'Spread sauce on both buns. Stack burgers with your favorite toppings.',
    ],
    category: 'Dinner',
    tags: ['Burgers', 'Beef', 'Quick', 'Grilling', 'American'],
    servings: '4 burgers',
    prepTime: '10',
    cookTime: '8',
    totalTime: '18',
    viewCount: 3200,
    saveCount: 480,
    publishedDaysAgo: 3,
  },
  {
    id: 'demo_grillmaster_brisket',
    sourceRecipeId: 'seed-uuid-033',
    creatorId: 'demo_grillmaster',
    creatorName: 'Marcus Johnson',
    creatorProfileSlug: 'marcus-johnson',
    title: 'Texas-Style Smoked Brisket',
    description:
      "The king of BBQ. A whole packer brisket done right is a thing of beauty - that smoke ring, that bark, that melt-in-your-mouth flat and juicy point. This takes all day, but trust me, it's the most rewarding cook you'll ever do.",
    ingredients: [
      '1 whole packer brisket (12-15 lbs)',
      '1/4 cup coarse black pepper',
      '1/4 cup coarse kosher salt',
      '2 tablespoons garlic powder',
      '1 tablespoon onion powder',
      'Yellow mustard (as binder)',
      'Oak or hickory wood chunks',
      'Beef tallow or butter (for wrapping)',
    ],
    instructions: [
      'Trim brisket: Remove excess fat, leaving 1/4 inch cap. Square off edges.',
      'Coat brisket lightly with mustard (this helps rub stick).',
      'Apply rub generously - mostly salt and pepper, Texas-style.',
      'Set smoker to 225-250°F with oak or hickory wood.',
      'Place brisket fat-side up. Smoke until bark forms and internal temp hits 165°F (about 6-8 hours).',
      'Wrap in butcher paper with a tablespoon of beef tallow.',
      'Continue cooking until internal temp reaches 200-205°F and probe slides in like butter.',
      'Rest wrapped in a cooler for at least 1 hour (up to 4 hours is better).',
      'Slice against the grain - thin slices for flat, thick cubes for point.',
    ],
    category: 'Dinner',
    tags: ['Brisket', 'Smoked', 'Texas BBQ', 'Low and Slow', 'Weekend Project'],
    servings: '20 servings',
    prepTime: '45',
    cookTime: '720',
    totalTime: '765',
    viewCount: 5800,
    saveCount: 920,
    publishedDaysAgo: 18,
  },
  {
    id: 'demo_grillmaster_grilled_wings',
    sourceRecipeId: 'seed-uuid-034',
    creatorId: 'demo_grillmaster',
    creatorName: 'Marcus Johnson',
    creatorProfileSlug: 'marcus-johnson',
    title: 'Crispy Grilled Buffalo Wings',
    description:
      "Forget the fryer - the grill gives you even crispier skin with that smoky flavor you can't get any other way. I use the two-zone method: crisp them over direct heat, then sauce them over indirect. Game day perfection.",
    ingredients: [
      '3 lbs chicken wings, tips removed and split',
      '2 tablespoons baking powder',
      '1 teaspoon salt',
      '1 teaspoon garlic powder',
      '1/2 teaspoon black pepper',
      '1/2 cup butter',
      '1/2 cup hot sauce (Frank\'s RedHot)',
      '1 tablespoon white vinegar',
      '1/4 teaspoon cayenne pepper',
      'Ranch or blue cheese dressing',
      'Celery and carrot sticks',
    ],
    instructions: [
      'Pat wings completely dry. Toss with baking powder, salt, garlic powder, and pepper.',
      'Refrigerate uncovered for 1 hour (or overnight for crispiest skin).',
      'Set up grill for two-zone cooking: hot direct heat on one side, no heat on other.',
      'Grill wings over direct heat, flipping every 3-4 minutes, until skin is crispy (15-20 minutes).',
      'Make sauce: Melt butter, whisk in hot sauce, vinegar, and cayenne.',
      'Move wings to indirect heat. Brush with sauce.',
      'Close lid and cook 5 more minutes.',
      'Toss wings in remaining sauce. Serve with dressing and veggie sticks.',
    ],
    category: 'Appetizer',
    tags: ['Wings', 'Buffalo', 'Grilled', 'Game Day', 'Party Food'],
    servings: '6 servings',
    prepTime: '15',
    cookTime: '25',
    totalTime: '100',
    viewCount: 2600,
    saveCount: 380,
    publishedDaysAgo: 5,
  },
  {
    id: 'demo_grillmaster_pulled_pork',
    sourceRecipeId: 'seed-uuid-035',
    creatorId: 'demo_grillmaster',
    creatorName: 'Marcus Johnson',
    creatorProfileSlug: 'marcus-johnson',
    title: 'Carolina Pulled Pork',
    description:
      "Nothing beats a pile of tender pulled pork with that tangy Carolina vinegar sauce. The pork shoulder is so forgiving - just keep it low and slow until it shreds like butter. I make a double batch because leftovers are incredible.",
    ingredients: [
      '1 bone-in pork shoulder (8-10 lbs)',
      '1/4 cup brown sugar',
      '2 tablespoons paprika',
      '2 tablespoons salt',
      '1 tablespoon black pepper',
      '1 tablespoon garlic powder',
      '1 tablespoon onion powder',
      '1 teaspoon cayenne',
      'Carolina vinegar sauce:',
      '1 cup apple cider vinegar',
      '1/2 cup ketchup',
      '1 tablespoon brown sugar',
      '1 teaspoon red pepper flakes',
      '1/2 teaspoon black pepper',
    ],
    instructions: [
      'Mix dry rub ingredients. Coat pork shoulder generously. Refrigerate overnight.',
      'Set up smoker for 225°F with hickory or apple wood.',
      'Smoke pork fat-side up for 10-12 hours until internal temp reaches 195-205°F.',
      'Spritz with apple cider vinegar every 2 hours after the first 4 hours.',
      'When pork is done (bone pulls out easily), wrap in foil and rest 1 hour.',
      'Make sauce: Whisk vinegar, ketchup, sugar, pepper flakes, and black pepper.',
      'Shred pork with forks or meat claws, discarding excess fat.',
      'Toss pulled pork with vinegar sauce to taste.',
      'Serve on buns with coleslaw or on a plate with sides.',
    ],
    category: 'Dinner',
    tags: ['Pulled Pork', 'Smoked', 'Carolina', 'BBQ', 'Crowd Pleaser'],
    servings: '16 servings',
    prepTime: '20',
    cookTime: '720',
    totalTime: '740',
    viewCount: 3900,
    saveCount: 580,
    publishedDaysAgo: 22,
  },
  {
    id: 'demo_grillmaster_grilled_corn',
    sourceRecipeId: 'seed-uuid-036',
    creatorId: 'demo_grillmaster',
    creatorName: 'Marcus Johnson',
    creatorProfileSlug: 'marcus-johnson',
    title: 'Elote-Style Grilled Corn',
    description:
      "The best side dish for any cookout. That char on the corn plus creamy, spicy, cheesy topping - it's addictive. I learned this from a street vendor in Mexico City and have been making it ever since. Your guests will fight over the last ear.",
    ingredients: [
      '6 ears corn, husked',
      '1/2 cup mayonnaise',
      '1/4 cup sour cream',
      '1 cup cotija cheese, crumbled',
      '2 tablespoons chili powder',
      '1 teaspoon smoked paprika',
      '1/4 teaspoon cayenne pepper',
      '2 limes, cut into wedges',
      '1/4 cup fresh cilantro, chopped',
      '2 tablespoons butter, melted',
    ],
    instructions: [
      'Preheat grill to medium-high heat.',
      'Brush corn with melted butter.',
      'Grill corn, turning every 2-3 minutes, until charred in spots (8-10 minutes total).',
      'Mix mayonnaise and sour cream in a bowl.',
      'Mix chili powder, paprika, and cayenne in a small bowl.',
      'While corn is hot, brush generously with mayo mixture.',
      'Sprinkle with cotija cheese - it will stick to the mayo.',
      'Dust with chili powder mixture.',
      'Squeeze lime over each ear and sprinkle with cilantro.',
      'Serve immediately while hot.',
    ],
    category: 'Side Dish',
    tags: ['Corn', 'Mexican', 'Grilled', 'Summer', 'Cookout'],
    servings: '6 servings',
    prepTime: '10',
    cookTime: '10',
    totalTime: '20',
    viewCount: 2200,
    saveCount: 340,
    publishedDaysAgo: 8,
  },
];

// ============================================================================
// Exports
// ============================================================================

export const ALL_RECIPES: SeedRecipe[] = [
  ...GRANDMAZING_RECIPES,
  ...PHILLIP_FRY_RECIPES,
  ...CHEF_MARIA_RECIPES,
  ...FITFOODIE_RECIPES,
  ...BAKINGBELLE_RECIPES,
  ...GRILLMASTER_RECIPES,
];

export function getRecipesByCreator(creatorId: string): SeedRecipe[] {
  return ALL_RECIPES.filter((r) => r.creatorId === creatorId);
}

export function getCreatorById(creatorId: string): DemoCreator | undefined {
  return DEMO_CREATORS.find((c) => c.id === creatorId);
}
